# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnorm2 <- function(x, mean, sigma, logd = FALSE) {
    .Call('JMbayes_dmvnorm2', PACKAGE = 'JMbayes', x, mean, sigma, logd)
}

lap_rwm_C <- function(initials, Data, priors, scales, Covs, control, interval_cens) {
    .Call('JMbayes_lap_rwm_C', PACKAGE = 'JMbayes', initials, Data, priors, scales, Covs, control, interval_cens)
}

lap_rwm_C_nogammas <- function(initials, Data, priors, scales, Covs, control) {
    .Call('JMbayes_lap_rwm_C_nogammas', PACKAGE = 'JMbayes', initials, Data, priors, scales, Covs, control)
}

lap_rwm_C_woRE <- function(initials, Data, priors, scales, Covs, control) {
    .Call('JMbayes_lap_rwm_C_woRE', PACKAGE = 'JMbayes', initials, Data, priors, scales, Covs, control)
}

lap_rwm_C_woRE_nogammas <- function(initials, Data, priors, scales, Covs, control) {
    .Call('JMbayes_lap_rwm_C_woRE_nogammas', PACKAGE = 'JMbayes', initials, Data, priors, scales, Covs, control)
}

logPosterior <- function(temp, event, idGK_fast, W1, W1s, Bs_gammas, W2, W2s, gammas, Wlong, Wlongs, alphas, Pw, mean_Bs_gammas, Tau_Bs_gammas, mean_gammas, Tau_gammas, mean_alphas, Tau_alphas, tauBs, A_tauBs, B_tauBs) {
    .Call('JMbayes_logPosterior', PACKAGE = 'JMbayes', temp, event, idGK_fast, W1, W1s, Bs_gammas, W2, W2s, gammas, Wlong, Wlongs, alphas, Pw, mean_Bs_gammas, Tau_Bs_gammas, mean_gammas, Tau_gammas, mean_alphas, Tau_alphas, tauBs, A_tauBs, B_tauBs)
}

logPosterior_nogammas <- function(temp, event, idGK_fast, W1, W1s, Bs_gammas, Wlong, Wlongs, alphas, Pw, mean_Bs_gammas, Tau_Bs_gammas, mean_alphas, Tau_alphas, tauBs, A_tauBs, B_tauBs) {
    .Call('JMbayes_logPosterior_nogammas', PACKAGE = 'JMbayes', temp, event, idGK_fast, W1, W1s, Bs_gammas, Wlong, Wlongs, alphas, Pw, mean_Bs_gammas, Tau_Bs_gammas, mean_alphas, Tau_alphas, tauBs, A_tauBs, B_tauBs)
}

gradient_logPosterior <- function(temp, event, idGK_fast, event_colSumsW1, W1s, Bs_gammas, event_colSumsW2, W2s, gammas, event_colSumsWlong, Wlongs, alphas, Pw, mean_Bs_gammas, Tau_Bs_gammas, mean_gammas, Tau_gammas, mean_alphas, Tau_alphas, tauBs, A_tauBs, B_tauBs) {
    .Call('JMbayes_gradient_logPosterior', PACKAGE = 'JMbayes', temp, event, idGK_fast, event_colSumsW1, W1s, Bs_gammas, event_colSumsW2, W2s, gammas, event_colSumsWlong, Wlongs, alphas, Pw, mean_Bs_gammas, Tau_Bs_gammas, mean_gammas, Tau_gammas, mean_alphas, Tau_alphas, tauBs, A_tauBs, B_tauBs)
}

gradient_logPosterior_nogammas <- function(temp, event, idGK_fast, event_colSumsW1, W1s, Bs_gammas, event_colSumsWlong, Wlongs, alphas, Pw, mean_Bs_gammas, Tau_Bs_gammas, mean_alphas, Tau_alphas, tauBs, A_tauBs, B_tauBs) {
    .Call('JMbayes_gradient_logPosterior_nogammas', PACKAGE = 'JMbayes', temp, event, idGK_fast, event_colSumsW1, W1s, Bs_gammas, event_colSumsWlong, Wlongs, alphas, Pw, mean_Bs_gammas, Tau_Bs_gammas, mean_alphas, Tau_alphas, tauBs, A_tauBs, B_tauBs)
}

